# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7986b628d34f3eb68f85a67aae14dcd6ae32c73be12f73660d7f98d489f689a62f330627e2c09c8fbc6fc3d1c27a9c64d12be5d1158dba8748898d67f7524dcf

test:
  secret_key_base: 5ead7b04c5fb688e2c105dc43bb5a1e773ff5f37612961bc0b691e327de475f09282fb65b11ea8d2453d5a4c7e381ca06f4b223d878ab22548631cd015b152ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
